## Numpy Array Operations:

### 1. Create a 1D NumPy Array:

In [1]:
import numpy as np

In [2]:
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

In [3]:
print(temperatures_w1)

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]

### 2. Inspection and Properties:

In [4]:
print(temperatures_w1.shape)

(7,)

In [5]:
print(temperatures_w1.dtype)

float64

In [6]:
print(temperatures_w1.size)

7

### 3. Array Operations:

In [7]:
Fahrenheit=(temperatures_w1*9/5)+35

In [8]:
print(Fahrenheit)

[75.5  80.54 72.44 77.12 81.98 79.64 74.42]

In [9]:
print(np.max(temperatures_w1))

26.1

In [10]:
print(np.min(temperatures_w1))

20.8

In [11]:
print(np.mean(temperatures_w1))

23.542857142857144

### 4. Array Slicing and Indexing:

In [12]:
print(temperatures_w1[:3])

[22.5 25.3 20.8]

In [13]:
print(temperatures_w1[5:])

[24.8 21.9]

In [14]:
print(temperatures_w1[3:6])

[23.4 26.1 24.8]

### 5. Create a 2D Array:

In [15]:
temperatures= np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]
])

### 6. Inspect and Slice the 2D Array:

In [16]:
print(temperatures.shape)

(2, 7)

In [18]:
print(temperatures.dtype)

float64

In [17]:
print(temperatures.size)

14

In [19]:
print(temperatures[0,-2:])

[24.8 21.9]

In [20]:
print(temperatures[1,-2:])

[22.8 20.1]

## Pandas Series:

### 1. Creating Pandas Series:

In [21]:
import pandas as pd

In [22]:
marks = pd.Series(
    [95,92,89,85,80],
    index=['Rank 1','Rank 2','Rank 3','Rank 4','Rank 5'])

In [23]:
print(marks)

Rank 1    95
Rank 2    92
Rank 3    89
Rank 4    85
Rank 5    80
dtype: int64

### 2. Indexing and Slicing:

In [24]:
print(marks.iloc[0])

95

In [25]:
print(marks.loc[['Rank 1','Rank 2','Rank 3']])

Rank 1    95
Rank 2    92
Rank 3    89
dtype: int64

In [26]:
print(marks.iloc[2])

89

In [27]:
print(marks[marks>90])

Rank 1    95
Rank 2    92
dtype: int64

### 3. Manipulating Series:

In [28]:
marks["Rank 1"]=100

In [29]:
print(marks)

Rank 1    100
Rank 2     92
Rank 3     89
Rank 4     85
Rank 5     80
dtype: int64

In [30]:
marks=marks.drop('Rank 5')

In [31]:
print(marks)

Rank 1    100
Rank 2     92
Rank 3     89
Rank 4     85
dtype: int64

In [32]:
cgpa = marks/10
print(cgpa)

Rank 1    10.0
Rank 2     9.2
Rank 3     8.9
Rank 4     8.5
dtype: float64

## Pandas DataFrame:

### 1. Creating Pandas DataFrame:

In [33]:
import pandas as pd

In [34]:
transactions = pd.DataFrame({
        'TransactionID':[101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory' :['Electronics', 'Clothing', 'Electronics', 'Furniture', 
                    'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
            'Region':['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 
                      'South', 'North'] ,
            'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400 ]})

In [35]:
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

### 2. Data Exploration:

In [36]:
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   TransactionID    10 non-null     int64
 1   ProductCategory  10 non-null     str
 2   Region           10 non-null     str
 3   Amount           10 non-null     int64
dtypes: int64(2), str(2)
memory usage: 593.0 bytes

In [37]:
transactions.head(5)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

In [38]:
transactions.tail(5)

   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [39]:
transactions.shape

(10, 4)

In [40]:
transactions.columns

Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='str')

In [41]:
transactions.dtypes

TransactionID      int64
ProductCategory      str
Region               str
Amount             int64
dtype: object

In [42]:
transactions[['ProductCategory','Amount']]

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400

In [43]:
transactions.iloc[-3:,:]

   TransactionID ProductCategory Region  Amount
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [44]:
transactions[(transactions['Region']=='North') & (transactions['Amount']>200)]

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400

In [55]:
transactions["ProductCategory"].value_counts()

ProductCategory
Electronics    4
Clothing       3
Furniture      2
Name: count, dtype: int64

In [45]:
transactions["Region"].unique()

<ArrowStringArray>
['North', 'South', 'East', 'West']
Length: 4, dtype: str

In [46]:
print(transactions.groupby("Region")["Amount"].mean())

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64

### 3. Manipulating the DataFrame:

In [47]:
transactions.loc[transactions["TransactionID"]==102, "Amount"]=165

In [48]:
def discount_10(x):
    return x * 10/100

In [49]:
transactions["Discount"]=transactions["Amount"].apply(discount_10)

In [50]:
print (transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0

In [51]:
transactions.drop(8,axis=0,inplace=True)

In [52]:
print (transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0

In [53]:
transactions.drop(["Discount"],axis=1,inplace=True)

In [54]:
print (transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400